// 类型定义统一导出

// API相关类型
export type {
  User,
  Order,
  Quote,
  Provider,
  LoginResponse,
  AuthUser,
  PaginatedResponse,
  AdminStats,
  UserActivity,
  WechatConfig,
  ApiError,
  PaginationParams,
  OrdersParams,
  UserActivityParams,
  CreateUserRequest,
  UpdateUserRequest,
  CreateOrderRequest,
  UpdateOrderRequest,
  CreateQuoteRequest,
  CreateProviderRequest,
  SelectProviderRequest,
  ExportResponse,
  BatchQuotesResponse,
  FileUploadResponse,
  UpdatePasswordRequest,
  ResetPasswordRequest,
  HealthCheckResponse,
  BackupConfig,
  BackupHistory,
  RestoreOptions,
  ApiResponse,
  HttpMethod,
  ApiRequestConfig,
  FormData,
} from './api';

// 通用类型
export type {
  ID,
  Status,
  Theme,
  Size,
  Variant,
  UserRole,
  OrderStatus,
  PaginationInfo,
  SortInfo,
  FilterInfo,
  TableColumn,
  FormField,
  MenuItem,
  BreadcrumbItem,
  Notification,
  ModalConfig,
  ConfirmConfig,
  FileInfo,
  UploadFileStatus,
  SearchConfig,
  ActionButton,
  StatCard,
  ChartData,
  TimeRange,
  Address,
  ContactInfo,
  ErrorBoundaryState,
  RouteGuard,
  AppConfig,
  UserPreferences,
  SystemStatus,
  KeyValuePair,
  DeepPartial,
  DeepRequired,
  RequiredFields,
  OptionalFields,
  AsyncFunction,
  EventHandler,
  ValueChangeHandler,
} from './common';
